# Generated by Django 4.2.23 on 2025-07-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Чек', 'verbose_name_plural': 'Чеки'},
        ),
        migrations.AddField(
            model_name='receipt',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ocr_technology',
            field=models.CharField(choices=[('tesseract', 'Tesseract OCR'), ('yandex_vision', 'Yandex Vision')], default='tesseract', max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('success', 'Успешно обработан'), ('error', 'Ошибка обработки')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
